// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQvvYVidqtWm3bqvJbKpeywyZJCFk5do4',
    appId: '1:186486904921:web:71ac330548bb4ae85eb948',
    messagingSenderId: '186486904921',
    projectId: 'projecopedia-food-recognizer',
    authDomain: 'projecopedia-food-recognizer.firebaseapp.com',
    storageBucket: 'projecopedia-food-recognizer.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYPj_IpYKqc_Tb4-z1ZjYgObkQDMCIH94',
    appId: '1:186486904921:android:47b82ba198da15bb5eb948',
    messagingSenderId: '186486904921',
    projectId: 'projecopedia-food-recognizer',
    storageBucket: 'projecopedia-food-recognizer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyB8Mp7XPEjQ_9VlWwxaQ006yFy0tqGtk',
    appId: '1:186486904921:ios:22061164b3ed33b25eb948',
    messagingSenderId: '186486904921',
    projectId: 'projecopedia-food-recognizer',
    storageBucket: 'projecopedia-food-recognizer.firebasestorage.app',
    iosBundleId: 'com.projecopedia.foodRecognizer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyB8Mp7XPEjQ_9VlWwxaQ006yFy0tqGtk',
    appId: '1:186486904921:ios:22061164b3ed33b25eb948',
    messagingSenderId: '186486904921',
    projectId: 'projecopedia-food-recognizer',
    storageBucket: 'projecopedia-food-recognizer.firebasestorage.app',
    iosBundleId: 'com.projecopedia.foodRecognizer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQvvYVidqtWm3bqvJbKpeywyZJCFk5do4',
    appId: '1:186486904921:web:3f2efac9965d51c35eb948',
    messagingSenderId: '186486904921',
    projectId: 'projecopedia-food-recognizer',
    authDomain: 'projecopedia-food-recognizer.firebaseapp.com',
    storageBucket: 'projecopedia-food-recognizer.firebasestorage.app',
  );
}
